# Generated by Django 2.2.5 on 2019-09-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('forget', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Emp',
            },
        ),
    ]
